# -*- coding: utf-8 -*-
"""Proyecto de investigación RODRIGO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-OXtr_2nv8bTcMqKacTT067OAZiNIZa
"""

import pandas as pd

import os 

tenorio = "https://www.datosabiertos.gob.pe/sites/default/files/DATOS_HIDROMETEREOLOGICOS_GORE_PIURA_2.csv"

df = pd.read_csv(tenorio)

df

!wget https://www.datosabiertos.gob.pe/sites/default/files/DATOS_HIDROMETEREOLOGICOS_GORE_PIURA_2.csv